name: Deploy Project
on:
  push:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.1
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Building the project
        run: |
          cd /home/runner/work/controleonline/controleonline
          echo "export const ENTRYPOINT_LOCAL = 'https://api.controleonline.com'" > ./src/config/entrypoint.local.js
          echo "export const DOMAIN_LOCAL = 'app.controleonline.com'" > ./src/config/domain.local.js
          yarn
          npm install
          npm update
          npx quasar build
          npx quasar build -m pwa
      - name: Copy to controleonline
        uses: horochx/deploy-via-scp@master
        with:
          local: /home/runner/work/controleonline/controleonline/dist/*
          remote: ~/sistemas/controleonline/app/dist
          host: sshproxy.cloudserver8.com
          port: 22212
          user: control2
          key: ${{ secrets.CONTROLEONLINE }} 